ARG BASE_TAG=latest
FROM $BASE_TAG

ENV PREFACTOR_DATA_ROOT=/usr/local/share/prefactor \
    PYTHONPATH=/usr/local/bin

# Install Prefactor CWL
COPY . /tmp/prefactor

RUN python3 -m pip install --no-cache-dir --upgrade /tmp/prefactor && \
    rm -rf /tmp/prefactor

# # A user 'lofaruser' is added (this might be legacy -- not sure this is
# # still relevant).
# RUN groupadd -r lofaruser && \
#     useradd -r -l -m -g lofaruser lofaruser

# WORKDIR /home/lofaruser

# USER lofaruser
