FROM lofareosc/prefactor3-cwl

RUN groupadd -r lofaruser && \
    useradd -r -l -m -g lofaruser lofaruser


RUN apt-get update && \
    apt-get install -y \
    python3-regex
RUN python3 -m pip install -Iv pyvo bdsf
#==0.9.3

RUN apt-get update && \
    apt-get install -y \
        git \
        cmake \
        python3-scipy \
        python3-statsmodels \
        python3-astroquery \
        python3-magic && \
    mkdir -p /src

# ensure that `python` and associated commands
# are available. Needed for facetselfcal.py
RUN cd "$(dirname $(which python3))" \
    && ln -s idle3 idle \
    && ln -s pydoc3 pydoc \
    && ln -s python3 python \
    && ln -s python3-config python-config

WORKDIR /home/lofaruser

USER lofaruser
#RUN git clone https://github.com/lonbar/VLBI-cwl.git /home/lofaruser/VLBI-cwl

ENV PYTHONPATH=/home/lofaruser/VLBI-cwl/scripts/:$PYTHONPATH \
    PATH=/home/lofaruser/VLBI-cwl/scripts:$PATH

# Install VLBI CWL
COPY . /home/lofaruser/VLBI-cwl
