FROM lofareosc/prefactor3-cwl

RUN groupadd -r lofaruser && \
    useradd -r -l -m -g lofaruser lofaruser

WORKDIR /home/lofaruser

RUN python3 -m pip install -Iv pyvo
#==0.9.3

USER lofaruser
#RUN git clone https://github.com/lonbar/VLBI-cwl.git /home/lofaruser/VLBI-cwl
ENV PYTHONPATH=/home/lofaruser/VLBI-cwl/scripts/:$PYTHONPATH
ENV PATH=/home/lofaruser/VLBI-cwl/scripts:$PATH

# Install VLBI CWL
COPY . /home/lofaruser/VLBI-cwl

#RUN apt-get update #&& \
    #apt-get install -y git
