FROM lofareosc/prefactor3-cwl

RUN python3 -m pip install -Iv pyvo==0.9.3
RUN apt-get update && \
    apt-get install -y git

RUN groupadd -r lofaruser && \
    useradd -r -l -m -g lofaruser lofaruser

WORKDIR /home/lofaruser

USER lofaruser
RUN git clone https://github.com/lonbar/VLBI-cwl.git /home/lofaruser/VLBI-cwl
ENV PYTHONPATH=/home/lofaruser/VLBI-cwl/scripts/:$PYTHONPATH
